# Generated by Django 4.1.3 on 2022-11-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
