# Generated by Django 4.1.3 on 2022-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_puchase',
            field=models.BooleanField(default=False),
        ),
    ]
